//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceProgram.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class output {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal output() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceProgram.Language.output", typeof(output).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed!.
        /// </summary>
        internal static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try again! See you next time, bye!.
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clouds.
        /// </summary>
        internal static string Clouds {
            get {
                return ResourceManager.GetString("Clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to go through the insert details again enter Yes, otherwise just type anything else:.
        /// </summary>
        internal static string ContinueInsert {
            get {
                return ResourceManager.GetString("ContinueInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if your email and password are correct!.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a file!.
        /// </summary>
        internal static string createFile {
            get {
                return ResourceManager.GetString("createFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a weather report file!.
        /// </summary>
        internal static string createWR {
            get {
                return ResourceManager.GetString("createWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a wrong email format!.
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not in the correct format!.
        /// </summary>
        internal static string emailFormat2 {
            get {
                return ResourceManager.GetString("emailFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, but the email was not sent!.
        /// </summary>
        internal static string EmailNotSend {
            get {
                return ResourceManager.GetString("EmailNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will ask you to enter some details so that we can send you a weather report file..
        /// </summary>
        internal static string EnterDetails {
            get {
                return ResourceManager.GetString("EnterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid file path:.
        /// </summary>
        internal static string EnterFilePath {
            get {
                return ResourceManager.GetString("EnterFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not found!.
        /// </summary>
        internal static string fileNotFound {
            get {
                return ResourceManager.GetString("fileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the csv file with the WeatherReport..
        /// </summary>
        internal static string fileWR {
            get {
                return ResourceManager.GetString("fileWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is the information you needed! Good luck astronaut!.
        /// </summary>
        internal static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, astronaut!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning.
        /// </summary>
        internal static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to send a email with!.
        /// </summary>
        internal static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records!.
        /// </summary>
        internal static string noRecords {
            get {
                return ResourceManager.GetString("noRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the email you gave above:.
        /// </summary>
        internal static string PasswordEmail {
            get {
                return ResourceManager.GetString("PasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        internal static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records in the list!.
        /// </summary>
        internal static string recordsList {
            get {
                return ResourceManager.GetString("recordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a sender email(note that it should be a gmail account):.
        /// </summary>
        internal static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address to which we will send the WeatherReport file:.
        /// </summary>
        internal static string SendToEmail {
            get {
                return ResourceManager.GetString("SendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent!.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So let&apos;s start!.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this file you will see for every parameter aggregate data and the data of the most appropriate launch day..
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to make a two-factor verification to your gmail account and create and use a app password!.
        /// </summary>
        internal static string twoFactor {
            get {
                return ResourceManager.GetString("twoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Report.
        /// </summary>
        internal static string wr {
            get {
                return ResourceManager.GetString("wr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a wrong file path!.
        /// </summary>
        internal static string WrongFilePath {
            get {
                return ResourceManager.GetString("WrongFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
